### ISSUE TITLE
install and use intructions

### ISSUE THREAD

**Issue by npsonis** [zmaroti/aHISplex#1]
Hi, can you add a README file with installation info and instructions of how to use this tool?
Thanks
Nikos

**Comment by npsonis** [comment]
I manage to run the script. I had to download the static glimpse v.2.0.0 libraries and make them executable and give the path into the script, and also correct the path of aHISplex_data since it is not in the bin directory. I get a message "ERROR: Phasing failed. Are all BAM files aligned to GRCh37? Check ./test/phase.log" and no bcf file is generated, although when I look at the log nothing seems off.
Note that I am using hs37d5 as a reference genome which is equivalent of GRCh37 (has the same names of chromosomes) but additional contigs such as decoy seqs etc.
This is a snipset of the log:

[GLIMPSE2] Phase and impute low coverage sequencing data
  * Authors              : Simone RUBINACCI & Olivier DELANEAU, University of Lausanne
  * Contact              : simone.rubinacci@unil.ch & olivier.delaneau@unil.ch
  * Version       	 : GLIMPSE2_phase v2.0.0 / commit = 3bed6d9 / release = 2022-12-07
  * Citation	         : BiorXiv, (2022). DOI: https://doi.org/10.1101/2022.11.28.518213
  *         	         : Nature Genetics 53, 120–126 (2021). DOI: https://doi.org/10.1038/s41588-020-00756-0
  * Run date      	 : 22/10/2024 - 15:52:01

Files:
  * Input BAM/CRAM       : [/mypath/myfile.bam]
  * Reference binary     : [./../aHISplex_data/ref_GRCh37/GRCh37_15_25687817_31030163.bin]
  * Output file          : [./test/bcf/GRCh37_15_25687817_31030163.bcf]
  * Output format        : [BCF format | ZLIB compression]

GLIMPSE_phase parameters:
  * Imputation model     : [Reference panel imputation]
  * Input region         : [Given by binary reference panel]
  * Output region        : [Given by binary reference panel]
  * Sparse MAF           : [Given by binary reference panel]
  * Recombination rates  : [Given by binary reference panel]
  * Ploidy               : [Only diploid samples in region]
  * Keep monom. ref sites: [NO]

Model parameters:
  * #Burnin iterations   : [5]
  * #Main iterations     : [15]
  * Ne [eff. pop. size]  : [100000]
  * Phase error rate     : [0.0001]
  * Imputation error rate: [1e-12]
  * Min value for hap GLs: [1e-10]

Selection parameters:
  * K init               : [1000]
  * K pbwt               : [2000]
  * PBWT depth           : [12]
  * PBWT modulo (cM)     : [0.1]
  * State list           : [No list provided]

Genotype calling:
  * Calling model        : [standard]
  * Perform calling]

BAM/CRAM filters and options:
  * Min mapping quality  : [10]
  * Min base quality     : [10]
  * Max depth            : [40]
  * Keep failed QC       : [NO]
  * Keep orphan reads    : [NO]
  * Keep duplicate reads : [NO]
  * Keep supp. alignment : [NO]
  * Check pairing        : [NO]
  * Ignore orientation   : [NO]
  * Illumina-1.3+        : [NO]

Other parameters
  * Seed                 : [15052011]
  * #Threads             : [1]

Initialisation:
  * Binary reference panel parsing ...
  * Binary reference panel parsing [done] (0.13s)
  * Binary reference panel [Nrh=5008] [L=138481] [Lrare= 89963 (65.0%) - Lcommon= 48518 (35.0%)]
  * Input region         : [15:25687817-31030163]
  * Output region        : [15:25687817-31030163]
  * Sparse MAF           : [0.001]
  * Reading BAM files
  * Reading BAM files [100%]
  * Reading BAM files done (2.04s)

**Comment by zmaroti** [comment]
Hi,

I am not sure whats wrong.  The hs37d5 ref should not be a problem (we use them as well because the added decoy sequences to capture the "junk"), as it has the same coordinates and naming covnention (without the chr pretag) as any other GRCh37 reference.

So far the feedback I got from two other researchers that it was easy to install/use.

```
git clone https://github.com/zmaroti/aHISplex
cd aHISplex
make
make install
```
The issue with the incompatible boots libraries across different GLIMPSE2 installations were reported by one user.  However the static v1.0 GLIMPSE2 binaries were working on other environments.

To compile the go tools you need a working go envrionment,  however I included the binaries so you can make install without building those and you should be ready to go.

It supposed to install the package to your user bin directory (~/bin) which is available in all major linux OS as far as I know. For me the Makefile seems very simplistic I cant imagine where it could fail.

May be you use some virtual environment and there is no disk space in your home/analysis directory. From the log it seems it could read the binary file. It seems phasing started and it could find the bam file and also the binary reference for the given chunk. Had you got any error at the end of the log?

Could you try to run the GLIMPSE2_phase_static with the following parameters:
`GLIMPSE2_phase_static --bam-file /mypath/myfile.bam --reference /PATH/TO/aHISplex_data/ref_GRCh37/GRCh37_15_25687817_31030163.bin --output test.bcf
`

And see if any error is thrown?

**Comment by npsonis** [comment]
I do not think that it is a glimpse issue as I run the proposed command and I get the bcf output (I am seeing the iterations of phasing etc). Note that GLIMPSE2_phase_static is not in my PATH.

Since there was no README file initially I did not compiled the program, so I modified the aHISplex.sh script as: 
DATA="$BINDIR/../aHISplex_data"
and
 G2PHASE=my_path/static_libraries_v2.0.0/GLIMPSE2_phase_static
 G2LIGATE=my_path/static_libraries_v2.0.0/GLIMPSE2_ligate_static

and then I run
bash aHISplex.sh -t 5 -o ./test -r GRCh37 test.bam
and gave the error that I issued


EDIT
Now it works after replacing DATA="$BINDIR/../aHISplex_data" with 
DATA="my_path/aHISplex/aHISplex_data" 


However, after your reply above I run

make 
go mod download
go build -o bin/transToHISplex     ./cmd/transToHISplex/
go build -o bin/classifHISplex     ./cmd/classifHISplex/

and then make install
install -D -t ~/bin bin/transToHISplex bin/classifHISplex bin/aHISplex.sh
install -d  ~/bin/aHISplex_data/  ~/bin/aHISplex_data/ref_GRCh37  ~/bin/aHISplex_data/ref_GRCh38  ~/bin/aHISplex_data/ref_hg19
install -m 644 -t ~/bin/aHISplex_data/ aHISplex_data/*.{tsv,txt}
install: cannot stat 'aHISplex_data/*.{tsv,txt}': No such file or directory
make: *** [Makefile:13: install] Error 1



PS line 188 in the sh: ecit (do you mean exit?)

**Comment by zmaroti** [comment]
With git clone you download the data from git to your source directory, that has exact dir structure as the repo, including the data dirs. You have to change your current working directory to the cloned repo:

`cd aHISplex`

Here if you listed the content of the main directory of the tool you should see everything that is in the repo, including the sub directory 'aHISple_data' (and also all of its prebuild data).

`make install`

should work from this directory. The source (where you downloaded) and the install dir (~/bin/) shouldn't be the same directory.

I don't see why install fails, if you have cloned the repo properly in the repo there are the sites (txt) and translate tables (tsv) files in the [data directory](https://github.com/zmaroti/aHISplex/tree/main/aHISplex_data).


ps: thanks for the typo it should be exit.

**Comment by npsonis** [comment]
Hi again,

yes I am aware that I have to cd in the aHISplex

To be careful I removed the previous directory and repeated
git clone https://github.com/zmaroti/aHISplex
cd aHISplex
make
make install

and I get the same error after make install

install -D -t ~/bin bin/transToHISplex bin/classifHISplex bin/aHISplex.sh
install -d  ~/bin/aHISplex_data/  ~/bin/aHISplex_data/ref_GRCh37  ~/bin/aHISplex_data/ref_GRCh38  ~/bin/aHISplex_data/ref_hg19
install -m 644 -t ~/bin/aHISplex_data/ aHISplex_data/*.{tsv,txt}
install: cannot stat 'aHISplex_data/*.{tsv,txt}': No such file or directory
make: *** [Makefile:13: install] Error 1

**Comment by npsonis** [comment]
So I modified the makefile as:
install -m 644 -t $(INST_DIR)/aHISplex_data/ aHISplex_data/*.t??

And it works. The problem was with the { } symbols I think. Maybe because I am using MobaXterm (I have met problems in the past with its text editor)...

Thanks again for helping me finding the issue. You may close this.

**Comment by zmaroti** [comment]
Thanks for debugging it! I use bash and it has some extended capabilities that don't exist in other shell environments (like the expansion of \*.{txt,tsv} to all .tsv and .txt files).

I will change the makefile to do it explicitly for the \*.txt and \*.tsv in different lines. I hope that the "\*" notation is supported by all shell environments. :-)
